# Site settings
title: klepsys.lt
url: https://www.klepsys.lt
description: "Tomas Klepšys"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/kleptography  

# Build settings
markdown: kramdown
permalink: pretty
